# Generated by Django 4.2.13 on 2025-10-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_de_paie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichepaie',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='employe',
            name='chef_famille',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employe',
            name='enfants_a_charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
