# Generated by Django 4.2.13 on 2025-10-09 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiche_de_paie', '0002_remove_fichepaie_date_creation_employe_chef_famille_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichepaie',
            name='employe',
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.DeleteModel(
            name='FichePaie',
        ),
    ]
